SHOW databases;

SELECT * FROM student;

UPDATE student SET STUDENT_NAME = "BHEEMA SAI"
WHERE STUDENT_DEPT = "ECE";

CREATE TABLE TEST(
STUDENT_ID INT PRIMARY KEY,
STUDENT_NAME VARCHAR(30),
STUDENT_CONTACT INT,
STUDENT_DEPT VARCHAR(10));

SELECT * FROM TEST;

-- STUDENT TABLE DATA IS BEING COPIED INTO TEST TABLE DATA
INSERT INTO TEST SELECT * FROM STUDENT;


-- TO ELIMATE A TABLE
-- TRUNCATE TABLE TEST;

-- DELETING ENTIRE ROW
-- DELETE FROM TEST WHERE STUDENT_NAME = "bHEEMA";


-- REMOVE AN ENTIRE TABLE FROM THE DATABASE.
-- DROP TABLE TEST;
