-- SELECT * FROM student;

-- ALTER TABLE student RENAME TO STUDENT_details;

-- ALTER TABLE STUDENT_DETAILS RENAME TO STUDENT;

-- -- REMOVES THE DATABASE.
-- DROP DATABASE RGM;

SELECT * FROM SALESMAN;

-- ADDING AN EXTRA COLUMN
ALTER TABLE SALESMAN ADD ADDRESS VARCHAR(20);

UPDATE SALESMAN SET ADDRESS = "ANANTAPUR";

-- COLUMN ELIMINATION
ALTER TABLE SALESMAN DROP COLUMN ADDRESS;

-- ALTER TABLE SALESMAN DROP COLUMN COMMISSION, DROP COLUMN CITY;